version: '3.1'

services:
  frontend:
    image: react
    container_name: client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - dev
    links:
      - dev:dev
    networks:
      - webnet
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    restart:  always
  dev:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: ./server
      target: development
      dockerfile: ./Dockerfile
    command: npm run start
    depends_on:
      - database
    links:
      - database:database
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    networks:
      - webnet

  database:
    image: library/postgres:11.7-alpine
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ../postgres:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
    networks:
      - webnet

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  webnet: